### ISSUE TITLE
Password managers do not work on login

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [jellyfin/jellyfin-vue#1428]
**Describe The Bug**

On login, if you have a password manager attempt to auto-fill your credentials, it will not work.

**Steps To Reproduce**

1. Go to login page
2. Click your user to log in as
3. Use any standard password manager to auto-fill your password
4. Press login and observe error for wrong password

**Expected Behavior**

It should send the password to the server as the pw manager put it in for a successful login.

**Logs**

**Screenshots**

**System (please complete the following information):**

- Platform: Any desktop
- Browser: Firefox/chromium
- Jellyfin Version: 10.7.6

**Additional Context**

This appears to be a dumb quirk of vuejs, I solved it in another project [here](https://github.com/hyalusapp/hyalus/pull/51) so theoretically just implement that fix here. I would implement it myself but 1. I don't want to look through any more js than I have to and 2. I explain in a bit more detail there exactly how this works, but in essence the default way vuejs looks for changes in a text box (to, say, update that value in the vuejs backend) is by human interaction, so the pw manager filling it in is not detected and is very frustrating and dumb. Just the wonders of working with js I guess.

**Comment by MrTimscampi** [comment]
To me, it seems more like a password manager issue than a Vue issue: any input changed should do so in a way that triggers the `input` event.

Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event):

> The input event fires when the value of an <input>, <select>, or <textarea> element has been changed. 

So, to be standards-compliant, the password manager should trigger that event if it fills something.

If you have a specific list of password managers that aren't working, I'd be interested in giving it a look. I already confirmed that the login works as intended with 1password.

**Comment by ThibaultNocchi** [comment]
It also does with Bitwarden iOS + Safari

**Comment by MrTimscampi** [comment]
Got confirmation of it working with KeepassXC as well.

**Comment by gidoBOSSftw5731** [comment]
I tested specifically with keepass tusk/owl, and I am fairly sure dashlane also has the same problem. One note is a "workaround" to this is to have it auto-fill the form and then edit the form in some way (like put a space and then remove it) which does properly update vuex. I can get a video of a test in a minute.

Also, this is specific to extensions inside of desktop browsers, afaik using a password manager on most mobile platforms is essentially the same as just copy/pasting your password into the box (as far as element updates go)

**Comment by MrTimscampi** [comment]
I understand what the issue is. What I'm saying is that I think it's more of a password manager issue than a Vue one.

My test was done with 1password's browser extension on Firefox 89, on Linux. So there's no desktop app or anything, it's all in-browser. And it works just fine, so I'd expect any well-implemented password manager to work just fine as well.

Tusk isn't triggering the proper events: https://github.com/subdavis/Tusk/blob/b3d2335168758ea67038fdb970b3430e737c2910/background/inject.js#L175-L191

It should also trigger `input` here, but it doesn't. If you add it there, it should work properly. Though do note that it isn't maintained anymore, so you might want to update to a newer/supported extension.  
Owl is archived as well, btw.

The keepassxs-browser extension will work just fine: https://github.com/keepassxreboot/keepassxc-browser/blob/81c6780272556c75bcd8ba15ee973db5c787ddb5/keepassxc-browser/content/keepassxc-browser.js#L1648-L1655

**Comment by gidoBOSSftw5731** [comment]
While I do get your point, and yes I do know that both owl and tusk are unmaintained, I would argue that meeting clients in the middle as they are right now is a better idea than saying that they don't technically follow the specification and offloading the work onto them. Still waiting on my tests for the dashlane/lastpass password managers to come in (I don't have an account with them so I'm asking someone else to do the test) but I do know that as of a month or so ago, dashlane did have the same issue. 

Password managers are often not well implemented as was mentioned before, but that's just where the playing field is right now.

**Comment by MrTimscampi** [comment]
> I would argue that meeting clients in the middle as they are right now is a better idea than saying that they don't technically follow the specification and offloading the work onto them

I would argue that it's not the website's job to adapt to tools, but the tool's job to adapt to websites.

Imo, asking the websites/webapps to change in order to support a tool is seeing the issue backwards. Most websites and webapps are not open source, and it's really the job of the tool to try to adapt to how the web works in practice, in my opinion.

**Comment by MrTimscampi** [comment]
To go further on that last thought: what if the issue was reversed?

If a password manager is triggering `input` and not `change`, your hack won't work either, putting another segment of users with a non-working auto-fill.

Anything we do to sidestep badly implemented password managers will leave us with a blind spot, unless we add like 5-6 event listeners on our own, which isn't a solution anybody would be willing to go down with.

**Comment by gidoBOSSftw5731** [comment]
For what it's worth, apparently Dashlane (and bitwarden) now works correctly, so I guess this issue has either been solved recently or I misunderstood the issue. Thanks for your time anyway.
