### ISSUE TITLE
[Docker - nginx] 404 when refreshing detail pages (/*/*)

### ISSUE THREAD

**Issue by doc-code-hub** [jellyfin/jellyfin-vue#1683]
### Description of the bug

I ran the latest unstable image on docker, on 80:80 but I have a problem.

Every time I refresh the page, this from 404, except for the paths / and / * /

Excluding Login and Host page, everything that is /*/* returns 404 (summing up, the detail pages).

Making a list:

It works
- Home
- Login / Host
- Settings
- Metadata

It does not work
- library/*
- item/*
- series/*

I don't have some types of elements and I don't know if there are other specific paths, however I think it is also reflected in any other detail pages.

### Steps to reproduce

docker pull jellyfin/jellyfin-vue:unstable
docker run -p 80:80 jellyfin/jellyfin-vue:unstable
Go to localhost (or wathever), login
Go to some library or item or series page
Refresh (F5) 

![image](https://user-images.githubusercontent.com/61033694/148853501-807016f1-4cc7-4cb3-94a2-78fb1a70f671.png)

### Expected behavior

The page reloads correctly

### Screenshots

![image](https://user-images.githubusercontent.com/61033694/148853819-d279ca3f-d65e-4ce9-80ec-389413d4315c.png)

### Platform

Windows

### Browser

Chrome

### Jellyfin server version

10.7.7

**Comment by ferferga** [comment]
This is something I thought about when casually exploring the Vue router docs for some information about the meta tags, so I think I might be helpful :).

I think the cause it's that [Vue router uses hashing mode by default](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations). Can you check by changing the [mode](https://router.vuejs.org/api/#mode) to ``history``, as we no longer need abstract for fallback since we don't use SSR anymore?

All browsers (even really ancient versions, which we no longer plan tu support) [supports the HTML5 History API](https://caniuse.com/mdn-api_history) so this shouldn't be a problem.

**Comment by ferferga** [comment]
This is something I thought about when casually exploring the Vue router docs for some information about the meta tags, so I think I might be helpful :).

I think the cause it's that [Vue router doesn't use hash mode, as there's no # appended to our urls (probably a Nuxt thing, as it's their default supposedly)](https://router.vuejs.org/guide/essentials/history-mode.html). Can you check by changing the [mode](https://router.vuejs.org/api/#mode) to ``hash``, as we no longer need abstract for fallback since we don't use SSR anymore?

**Comment by doc-code-hub** [comment]
`Can you check by changing the mode to history, as we no longer need abstract for fallback since we don't use SSR anymore?`

Sure, i'm on it

**Comment by ferferga** [comment]
Try both just in case, which one we use shouldn't really matter now.

**Comment by doc-code-hub** [comment]
With `'hash'`  unfortunately it doesn't work.

in this way the links of the side drawer (library / id) work.

The redirects of the individual elements seem not to work at all, despite modifying the path (but incorrectly, they seem to go to library / id).

Maybe they redirect differently from the drawer?

![image](https://user-images.githubusercontent.com/61033694/148858439-10002481-cfde-45a4-885b-8decbf5b3603.png)

_series navigate (that doesn't work)_
![image](https://user-images.githubusercontent.com/61033694/148858463-9a2fb576-810f-417e-ba76-42331639bfed.png)

Anyway I wonder if there is anything that can be done at the nginx.conf level to successfully support the 'history' mode

**Comment by ferferga** [comment]
Yes it can, but I'd rather have this fixed so users don't need to mangle their setups unnecessarily.

I'll check this as well when I have some spare time from exams.
