### ISSUE TITLE
Can't click on "View details" on iOS browsers

### ISSUE THREAD

**Issue by ThibaultNocchi** [jellyfin/jellyfin-vue#1702]
### Description of the bug

On iOS browsers (Safari, Firefox, PWA...) clicking on the "View details" buttons on the home carousel.

### Steps to reproduce

- Open the website on an iOS device (tested iPhone and iPad)
- Click "View details" on an item
- It does nothing

### Expected behavior

It should work as on desktop

### Platform

iOS

### Browser

Safari

### Jellyfin server version

10.7.7

**Comment by doc-code-hub** [comment]
I don't have any apple devices, 
but tonight I can borrow it from a family member and try to figure out what the problem is, 

if nobody plans to beat me on time. :) In case you let me know so I give up

**Comment by doc-code-hub** [comment]
So, 
_I actually encountered the problem you report_, on iphone X and safari. (It just seems to show 'hover' and do nothing)

I also found that in addition to "View Details", the "Play" button and title link do not work either. (this would make me point the finger at swiper)

I also get a flicker on the backdrop photo when one of the 3 mentioned above is clicked (every now and then, I still don't know based on what).

The only way that results to perform the action is to hold down and click the "Open" option (at present).

### Summing up:
Since I have not encountered other problems on the various buttons in the other pages (as below in the home) 
I would like to say (with some certainty) that the problem is **due to the behavior of Swiper** in medium-small IOS devices.

--------------

Unfortunately, I am a bit inconvenient to serve the app on the iphone in a local environment using WSL as a development environment, and I only have this device (iphone X) available during the evening.

### For the moment, unfortunately, that's all I can add, but is a starting point :)

I don't know if @ferferga maybe, who (seeing from gitlense) seems to have implemented swiper, comes to mind something related to swiper (who surely knows better than me) that maybe it could cause this strange behavior for ios? :)

_When I can I will try to continue to deepen and look for a solution._

**Comment by ThibaultNocchi** [comment]
Fixed by the migration to Vue 3.
