### ISSUE TITLE
Resizing the window sends a lot of requests

### ISSUE THREAD

**Issue by MBR-0001** [jellyfin/jellyfin-vue#1888]
### Description of the bug

Resizing the window sends a lot of web requests for images, many of them being canceled

https://user-images.githubusercontent.com/55142207/219977861-b72f051c-ace7-4f29-962a-e8ddc0ab19c7.mp4

### Steps to reproduce

Resize the window

### Expected behavior

Resize events are debounced? 

### Screenshots

![image](https://user-images.githubusercontent.com/55142207/219978041-013bc96b-7da3-48dd-9986-cfcb9a318231.png)

### Platform

Linux

### Browser

Other (Please specify in the "additional context" section)

### Jellyfin server version

10.8.9

### Additional context

```text
Brave browser, vite branch https://github.com/jellyfin/jellyfin-vue/commit/82b559c754089b6872759429af584bd01b6f0678
```

**Comment by HEPOSHEIKKI** [comment]
Most of the requests fortunately return [304 Not Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) which cuts down on bandwith usage, but this should still be adressed since the hundreds of requests add up to a few dozed megabytes on my instance which is still a bit unnecessary.
