### ISSUE TITLE
Insanely cpu use on firefox+linux

### ISSUE THREAD

**Issue by mjwells2002** [jellyfin/jellyfin-vue#2263]
### Description of the bug

homepage uses very large amounts of cpu on firefox + linux around 60-70%, and general page loading/rendering is extremely slow, chrome on the same system results in normal use at around 0.5-1%, firefox profiler seems to show canvas rendering taking all the cpu time

### Steps to reproduce

open homepage in firefox on linux

### Expected behavior

cpu use normal, page renders fast

### Screenshots

![image](https://github.com/jellyfin/jellyfin-vue/assets/36360408/0da1d7a2-380b-42d4-9de2-78693dd08580)
![image](https://github.com/jellyfin/jellyfin-vue/assets/36360408/7cc01a98-29ee-4557-b2ac-19e683bb2923)

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.13

### Additional context

```text
system is running kde fedora 39, kde 5.27.10, kernel 6.7.7 on a ryzen 5 5500 + 6700xt
```

**Comment by ferferga** [comment]
How do you think we're expected to fix this? There are some minor rerenders on home page load due to swiper which I know that can be improved (not everything rerenders anyway) and blurhash resolution can be reduced to half (as in current web, though it's higher since this is not expected to run on older engines and modern engines are faster, plus most devices that have modern engines are also powerful), but they won't solve the root cause. There's little room of improvement here. 

It looks like that Firefox isn't doing 2D GPU acceleration for you, which is another thing you can try first. Sadly the most likely solution is to switch to Chrome (or another Chromium based browser). You already discovered one of the reasons why Firefox is still lagging behind in usage quotas.

**Comment by mjwells2002** [comment]
Yea, im going to close this, just wanted to post it to provide context for anyone else who might run into the same issue, 
i tried to look into anything thats using the canvas api inside webworkers as that is what firefox is missing hw accel for on linux platforms but i couldnt find anything,

removing blurhash results in the same perfomance issue so im not sure what about this page causes it to become so slow, but will leave this issue here for anyone who may have this problem in the future
