### ISSUE TITLE
error yarn install

### ISSUE THREAD

**Issue by petitbou0169** [jellyfin/jellyfin-vue#232]
hello

> root@debian:/home/jellyfin-vue# yarn install
> yarn install v1.22.5
> warning You are using Node "16.0.0-pre" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error ts-node@9.0.0: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "16.0.0-pre"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by ferferga** [comment]
@petitbou0169 The error is clearly stated in the logs: you're using a beta of node for building the web client, while you need an stable version. Head over https://github.com/nodesource/distributions/blob/master/README.md and follow the installation instructions for node 15.

Closing this as this issue is not related to our repo.
