### ISSUE TITLE
document.fonts.keys() is not iterable on Firefox

### ISSUE THREAD

**Issue by EffakT** [jellyfin/jellyfin-vue#2432]
### Description of the bug

The recent change to ensure all resources are loaded before mount causes a bug in Firefox, as document.fonts does not return an Iterator in Firefox, rather a FontFaceSetIterator.

See below bugreport @ Mozilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1311198

There is a potential fix by Sidney Liebrand
https://sidneyliebrand.io/blog/fixing-font-face-set-entries-not-iterable-in-firefox

### Steps to reproduce

Load current release in firefox

### Expected behavior

Page should load

### Platform

macOS

### Browser

Firefox

### Jellyfin server version

10.9.2

**Comment by ferferga** [comment]
What a bad joke... 😓

There was a reason why that branch wasn't merged yet, not only because it's unfinished, but for testing it properly. Thought this change would be harmless and since I'm on vacation just with my laptop (no Firefox installed) just omitted checking it completely.

I'll try to open a PR later today.
