### ISSUE TITLE
[Feature] Make a collections page

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-vue#760]
**Describe The Bug**

Collections are displayed only as one item, and I'm unable to choose which item in the collection to play (the only options available are play and shuffle). The indicator displays the correct number of items in the collection though.

**Comment by Perseusdehond** [comment]
As of right now, there hasn't been anyone who made a proper item page for this. That is why they don't show up for now. My guess is that this will be implemented at some point (soon?). 
Alternatively instead of only showing just the movies, I have also made a design myself https://github.com/jellyfin/jellyfin-vue/discussions/478 for the collections item page for if anyone wants to spend the time to add something like that :)

**Comment by krutburken** [comment]
Ah I see, I just looked through the issues and saw that no-one had reported on it. Should maybe be changed to a feature request then?

For me it would be fine if it just replicated the current "folder" behavior as seen in jellyfin-web, but I guess it depends on the use case.

**Comment by Perseusdehond** [comment]
> Ah I see, I just looked through the issues and saw that no-one had reported on it. Should maybe be changed to a feature request then?
> 
Yeah, I think that is better.
> For me it would be fine if it just replicated the current "folder" behavior as seen in jellyfin-web, but I guess it depends on the use case. Jellyfin-web in general looks pretty outdated and bare-bones though so I'm really looking forward to this project reaching feature parity
>
I agree with that. I make those design ideas as an inspiration of what Vue could look like because I really like this project. 
I would be fine with just showing the movies at first so the collections would work at least. But my design is more of a not-super-bland-way to show these and imo a cool way to evolve the client

**Comment by ferferga** [comment]
Implemented in #1680

Some design concepts are still present in discussions that are also relevant and can inspire for further work in this area
