### ISSUE TITLE
[ux] clipping browser window to half of a 1080 display

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin-vue#891]
Two issues:
My usage habit, which can't be too uncommon, is to clip my browser window to 50% of my display. When I do this with my 1080p screen at 100% zoom, the page layout shifts to mobile.
1) Upon resizing the window the left navigation bar persists and needs to be closed manually. It should close by default. #920 

2) When the window is at 50% width of a 1080p display at 100% zoom, I really don't think I should be kicked to the mobile layout (at least as it relates to music). I don't think the argument can be made for button clutter at this width for both the bottom overlay and the bottom bar for the fullscreen player. I can zoom out to 95% in the browser and bypass all of this, but that shouldn't be necessary. Here are two screenshots at 100% and 95%, respectively--at 100% zoom on a 1080p screen, it should look more like it does at 95% zoom currently. The mobile interface, perhaps, should be invoked when the window is at 50>x% instead.

![image](https://user-images.githubusercontent.com/1365322/111520252-5046e180-872e-11eb-9c95-4073b0b2714f.png)

![image](https://user-images.githubusercontent.com/1365322/111520277-55a42c00-872e-11eb-8e4a-b54a1017da7f.png)

**Comment by MrTimscampi** [comment]
> the page layout shifts to mobile

For the first point, I do agree with you. We've had it on our radar for a while, but more important stuff keeps getting pushed in front of fixing it :smile: 

For the second point, I am guessing your issue is due to window decorations. Here's how it looks for me (GNOME at 1920x1080 with 1px wide window borders):
![image](https://user-images.githubusercontent.com/19396809/112145461-adcda900-8bda-11eb-9055-8539290ba829.png)

The fullscreen music UI is also not responsive yet, so that's one thing to note :yum: We could probably adjust the breakpoints a bit to better cover real world device, though we are using the default Vuetify ones currently, which seem to align with [Google's Material Design specs](https://material.io/design/layout/responsive-layout-grid.html#breakpoints), so I would be inclined to keep them as-is (On the basis of them having proper designers and being able to test on a wider selection of devices).

We can probably adjust some of the lower-size designs though (The two column things on the tablet size doesn't seem very good, for example).

**Comment by neopc10** [comment]
Regarding point #2, it's just straight up Microsoft Windows. I don't think the window borders can be modified here.
